dataset:

    batch_size: 16
    num_workers: 16

    random_flip: True
    random_crop: True
    color_jitter: False
    random_rotate: False

    mean: [0., 0., 0.]
    std: [1., 1., 1.]


training:

    epochs: 350
    optim: 'AdamW'
    base_lr: 0.00010
    weight_decay: 0.00005
    scheduler: 'CosineAnnealingWarmUpRestarts'
    gamma: 0.8
    T_0: 60
    T_up: 6
    lr_max: 0.00020
    lr_min: 0.00005

    loss_recon_coef: 1
    loss_perceptual_coef: 0.05


testing:

    start_eval_epoch: -1
    resol: '480p'     # ['480p', '4k']


network:

    n_points: 17
    hidden_dim: 128

    n_down_layer: 3
    n_attn_module: 3
    n_enc_block: [2, 2, 2]
    n_dec_block: [2, 2, 2]
    n_enc_heads: [8, 8, 8]
    n_dec_heads: [1, 1, 1]

